const ORDER_STATUSES = {
  NEW: "NEW",
  PREPARING: "PREPARING",
  READY: "READY",
  SERVED: "SERVED",
};

const PAYMENT_STATUSES = {
  UNPAID: "UNPAID",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  PAID: "PAID",
};

const TABLE_STATUSES = {
  EMPTY: "EMPTY",
  OCCUPIED: "OCCUPIED",
  AWAITING_PAYMENT: "AWAITING_PAYMENT",
};

const ORDER_SOURCES = {
  CUSTOMER: "CUSTOMER",
  WAITER: "WAITER",
};

module.exports = {
  ORDER_STATUSES,
  PAYMENT_STATUSES,
  TABLE_STATUSES,
  ORDER_SOURCES,
};
